-- Catálogo global de productos (`productos`).
--
-- El catálogo arranca vacío y crece cuando cada organización confirma productos
-- en una recepción (EAN, visión o alta manual). No hay siembra obligatoria.
--
-- Para vaciar un entorno de desarrollo (kits, demandas, reservas y catálogo):
--   pnpm --filter api db:reset-catalogo
--
-- Este archivo queda como referencia histórica; no inserta filas.
